### ISSUE TITLE
Remove requirement for actions to be plain objects and contain a type key

### ISSUE THREAD

**Issue by MattRoelle** [pyericz/redux-lua#5]
Hi there! 

Would you be open to removing these assertions and allowing actions to be passed through to the reducers directly as `...`?

https://github.com/pyericz/redux-lua/blob/4ee29d807f807e90e49a230e05cc243e4e95cf7a/src/createStore.lua#L175-L182

This would enable the end user to have more freedom regarding how to structure their code. This also should not be a breaking change.

----------

My selfish reason is that I am using the [Fennel language](https://fennel-lang.org) and enjoy using the clever `match` macro to destructure the actions. Something like:

```fnl
(fn my-reducer [state ...] 
  (match ...
    (:foo value) (merge state {:foo value})
    _ initial-state))
; ...
(store:dispatch :foo 100)
```

**Comment by pyericz** [comment]
Sorry Matt, I'm afraid these error statements must remain as they are. Error must be reported here,  and `error` and `assert` are the native uses of Lua error reporting, which are more applicable to most users.
